name: IC
on:
  pull_request:
    branches: [ "main" ]
jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: nuffem/0
        ref: bfd9cec44eb2635b4fc0a84ca2a88cb3b9e6551a
        path: "./0"
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: node 0/código/0_node.js testes/0