name: IC
on:
  pull_request:
    branches: [ "main" ]
jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: nuffem/0
        ref: 88918e326d521caeaee0ee1525ec0aac62f7ba8c
        path: "./0"
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: node 0/0_node.js testes/0